[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn backend.wsgi:application"
healthcheckPath = "/admin/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
