services:
  - type: web
    name: blog-platform-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: blog-platform-db
          property: connectionString

databases:
  - name: blog-platform-db
    databaseName: blogdb
    user: blog_user
